spring.application.name=secureChat

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/securechat
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect